#ifndef HARDWARE_CONFIG_INCLUDED
#define HARDWARE_CONFIG_INCLUDED

//=== Timer ===================================================================
#define MAIN_TIMER_INTERRUPT TIMER0_COMPA_vect
#define MAIN_TIMER_PRESCALE 8
#define MAIN_TIMER_PRESCALE_MASK _BV(CS01)
#define MAIN_TIMER_FREQUENCY 10000UL // Hz
#define MAIN_TIMER_MICROSECONDS (1000000UL / MAIN_TIMER_FREQUENCY)

//=== Pushbuttons =============================================================
#define PUSHBUTTON_PORT PORTB
#define PUSHBUTTON_DDR  DDRB
#define PUSHBUTTON_IN   PINB

#define PUSHBUTTON_LEFT_DOWN  PB4
#define PUSHBUTTON_LEFT_UP    PB5
#define PUSHBUTTON_RIGHT_DOWN PB6
#define PUSHBUTTON_RIGHT_UP   PB7

#define PUSHBUTTON_LSB PUSHBUTTON_LEFT_DOWN
#define PUSHBUTTON_MSB PUSHBUTTON_RIGHT_UP
#define PUSHBUTTON_COUNT ((PUSHBUTTON_MSB + 1) - PUSHBUTTON_LSB)

#define PUSHBUTTON_ALL_BUTTONS_MASK \
    (_BV(PUSHBUTTON_LEFT_DOWN) | _BV(PUSHBUTTON_LEFT_UP) \
    | _BV(PUSHBUTTON_RIGHT_DOWN) | _BV(PUSHBUTTON_RIGHT_UP))

//=== Rotary Encoder ==========================================================
#define ROTARY_DATA_BITS   12
#define ROTARY_STATUS_BITS 4
#define ROTARY_MAX_VALUE  (1 << ROTARY_DATA_BITS)
#define ROTARY_LOWER_MARK (ROTARY_MAX_VALUE / 3)
#define ROTARY_UPPER_MARK (2 * (ROTARY_MAX_VALUE / 3))


#define ROTARY_SPI_PORT    PORTC
#define ROTARY_SPI_PORT_IN PINC
#define ROTARY_SPI_DDR     DDRC

#define ROTARY_CS_PORT     PORTD
#define ROTARY_CS_PORT_IN  PIND
#define ROTARY_CS_DDR      DDRD

#define ROTARY_V_DO  PC7
#define ROTARY_V_CLK PC6
#define ROTARY_V_CS  PD0

#define ROTARY_H_DO  PC5
#define ROTARY_H_CLK PC4
#define ROTARY_H_CS  PD1

#define ROTARY_DO_MASK  (_BV(ROTARY_V_DO)  | _BV(ROTARY_H_DO))
#define ROTARY_CLK_MASK (_BV(ROTARY_V_CLK) | _BV(ROTARY_H_CLK))
#define ROTARY_CS_MASK  (_BV(ROTARY_V_CS)  | _BV(ROTARY_H_CS))

#define CAMERA_POWER_DDR DDRB
#define CAMERA_POWER_PORT PORTB
#define CAMERA_POWER_PORT_IN PINB
#define CAMERA_POWER_PIN PB0

#define BOOTSECTOR_SIZE 4096
#define BOOTLOADER_START_ADDRESS  (FLASHEND - BOOTSECTOR_SIZE)

#endif // HARDWARE_CONFIG_INCLUDED
